Jira Service Connection
cloud-bulldozer/cpt-dashboard pull request #59
Opened 2023-11-28 21:25 UTC by mfleader

## Type of change

- [ ] Refactor
- [X] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Add a connector for Jira.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

2023-11-30 07:57 UTC, chentex commented on backend/app/api/v1/endpoints/cpt/jira.py
I am not a 100% convinced this endpoint should be here, but for the moment let's just keep it here, and see how it's use evolves.

2023-11-30 07:57 UTC, chentex approved these changes
LGTM

2023-12-01 07:30 UTC, chentex commented on backend/app/api/v1/endpoints/cpt/jira.py
Yes, that was what I meant, but as I said let's leave it there for the moment, and see how the API evolves to see if we need to move it around.

2023-12-05 09:46 UTC, athiruma commented
Why do we need to create this endpoint when Jira already has an [API endpoint](https://developer.atlassian.com/server/jira/platform/jira-rest-api-example-query-issues-6291606/)?
If we need to use it within other endpoints or mappers, we can create a class to access the Jira APIs

2023-12-05 19:42 UTC, mfleader commented
@athiruma fair question.

I see it as a trade off between writing and maintaining our own Jira API types and data hooks in JavaScript or TypeScript (or working with another community project like [jira.js](https://github.com/mrrefactoring/jira.js/) or [jira-client](https://github.com/jira-node/node-jira-client)), or adding an endpoint that uses the Atlassian supported [Python API to Jira](https://github.com/atlassian-api/atlassian-python-api).

2023-12-05 19:54 UTC, mfleader commented
Somewhat in line with @chentex said, I think as we determine what needs to be queried on the Jira API for the dashboard the trade-off of this endpoint's existence should be re-evaluated. 

At the moment, I do not know what the UI needs from Jira, so this is a flexible solution.

2023-12-05 20:00 UTC, vishnuchalla commented
Just curious, why do we need this JIRA connection? Just trying to understand the purpose of it.

2023-12-07 09:37 UTC, chentex requested changes
Since I see most of us have doubts about this I propose the following steps:

1. @mfleader has already provided a `Jira Service` that could be used by any teams if they need to query something from `Jira` to their custom pages, that is a win and is done in a way any team could use it eventually.
2. Remove the enpoint, my reasoning:
   1. We do not have plans on displaying raw `Jira` data in the dashboard.
   2. If at some point it is needed to display something, I am sure that data would need to be formatted to a state that the UI could take and display it in a custom UI component, so probably the team doing that would use a specific new endpoint for that part and use the already provided `Jira` service to query their data and then clean it up to display it.

Please let me know if you agree with this @mfleader @athiruma @vishnuchalla

2024-01-08 18:10 UTC, mfleader commented
> Since I see most of us have doubts about this I propose the following steps:
> 
> 1. @mfleader has already provided a `Jira Service` that could be used by any teams if they need to query something from `Jira` to their custom pages, that is a win and is done in a way any team could use it eventually.
> 2. Remove the enpoint, my reasoning:
>    
>    1. We do not have plans on displaying raw `Jira` data in the dashboard.
>    2. If at some point it is needed to display something, I am sure that data would need to be formatted to a state that the UI could take and display it in a custom UI component, so probably the team doing that would use a specific new endpoint for that part and use the already provided `Jira` service to query their data and then clean it up to display it.
> 
> Please let me know if you agree with this @mfleader @athiruma @vishnuchalla

By already provided Jira service, do you mean the underlying Jira service that this endpoint is using?

From the conversations outside of this PR, it sounds like folks do want some sort of Jira endpoint here.

I think my point about using [Atlassian's supported Python API](https://github.com/cloud-bulldozer/cpt-dashboard/pull/59#issuecomment-1841504359) still stands.

2024-01-09 08:50 UTC, chentex requested changes
Since the time of my suggestions seems that now there is a need for the endpoint, so scratch all of that,
Seems that the consensus is to provide a JQL to the endpoint to get the needed fields.
i added some comments to reorganize the PR, to merge it after.

2024-01-09 08:50 UTC, chentex commented on backend/app/api/v1/endpoints/cpt/jira.py
Can you move this to  a new folder called `jira`, inside the `endpoints` folder

2024-01-09 08:50 UTC, chentex commented on backend/app/api/api.py
> +router.include_router(jira.router, tags=['cpt.jira'])
Separate to a new tag, maybe just call it `jira`

2024-01-09 08:50 UTC, chentex commented on backend/app/services/jira_svc.py
> +        self.pat = self.cfg.get(configpath+'.personal_access_token')
Can you add a section in the README explaining this fields

2024-01-09 08:50 UTC, chentex commented on backend/skeleton.toml
> +host_url=
This `host_url` doesn't match the one used in the `JiraService` class, and the `personal_access_token` is missing.

2024-01-23 08:09 UTC, chentex approved these changes
/lgtm thanks for the changes @mfleader

2024-01-23 17:02 UTC, dustinblack approved these changes
LGTM

2024-01-24 16:02 UTC, merged

2024-01-24 16:02 UTC, chentex commented
Thanks for the contribution @mfleader !